### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type X  with an ASP.NET Core Web Application (.NET Core 2.0)

### ISSUE THREAD

**Issue by bounav** [seesharper/LightInject.Microsoft.DependencyInjection#21]
Hello,

With a brand spanking new ASP.NET Core Web Application project, the controller dependencies are not resolved.
I get this exception: on locahost:xxx/foo

```bash
System.InvalidOperationException: Unable to resolve service for type 'WebApplication2.IFoo' while attempting to activate 'WebApplication2.Controllers.FooController'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

I'm hopping I missed a step somewhere!

In Visual Studio 2017 v15.5.7, I created a new ASP.NET Core Web Application project.

Then I followed the instructions on https://github.com/seesharper/LightInject.Microsoft.DependencyInjection.

Ran:

```
Install-Package Lightinject
Install-Package Lightinject.Microsoft.DependencyInjection
```

Got Lightinject `v5.1.2` and Lightinject.Microsoft.DependencyInjection `v2.0.5` listed as dependencies.

Then created the following classes:

```csharp
namespace WebApplication2
{
     public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            var containerOptions = new ContainerOptions {EnablePropertyInjection = false};
            
            var container = new ServiceContainer(containerOptions);

            container.Register<IFoo, Foo>();
            
            container.CreateServiceProvider(services);

            services.AddMvc().AddControllersAsServices();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

And an `IFoo` interface and dummy implementation:

```csharp
namespace WebApplication2
{
    public interface IFoo
    {
    }

    public class Foo : IFoo
    {
    }
}

```

And a `FooController` as well:

```csharp
namespace WebApplication2.Controllers
{
    public class FooController : Controller
    {
        public FooController(IFoo foo)
        {
            var test =  foo;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}
```

It looks like Microsoft's DI is kicking in instead of Lightinject's?

I was able to replicate the same error in another web project created against .NET Core 1.1.

**Comment by seesharper** [comment]
You should return the service provider in `ConfigureServices` method.

aka 
```
return container.CreateServiceProvider(services);
```

**Comment by bounav** [comment]
Oh, but isn't the `ConfigureServices()` the [method](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup) `void` method?

**Comment by seesharper** [comment]
Excellent 👍
